language: cpp
compiler:
- g++
os:
- linux
git:
  submodules: true
env:
  - DO_ENABLE_SH4_MMU=OFF
  - DO_ENABLE_SH4_MMU=ON
script:
  mkdir build ;
  cd build ;
  cmake -DENABLE_SH4_MMU=$DO_ENABLE_SH4_MMU .. || exit 1;
  make || exit 1;
  ./sh4asm_test && ./sh4mem_test && ./sh4inst_test && ./sh4tmu_test && ./sh4div_test
