name: CI build

on: [push]

jobs:
  build:

    strategy:
      matrix:
        mmu_enabled: [ Off, On ]
        invariants : [ Off, On ]
        os : [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: dependencies (linux only)
      run: sudo apt-get -y install libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libgl-dev libglu-dev libxi-dev
      if: "contains(matrix.os, 'ubuntu')"
    - uses: lukka/run-cmake@v2
      with:
        cmakeAppendedArgs: '-DENABLE_MMU=${{ matrix.mmu_enabled }} -DINVARIANTS=${{ matrix.invariants }}'
        cmakeBuildType: RelWithDebInfo
